import './style.css';
import Header from 'src/shared/widgets/header';
import { Toaster } from '@shadcn/components/sonner';
import Providers from '../providers/providers';

export const metadata = {
  title: 'Welcome to user-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>
          <Header />
          <main className='px-12 py-5'>
            {children}
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
