import './style.css';
import Header from 'src/shared/widgets/header';
import { Toaster } from '@shadcn/components/sonner';
import { ThemeProvider } from '@market-hub/packages/ui/shadcn/src/components/providers/theme-provider';

export const metadata = {
  title: 'Welcome to user-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Header />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className='px-12 py-5'>
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
